### ISSUE TITLE
Music auto-plays when receiving call

### ISSUE THREAD

**Issue by joshuaohana** [steve228uk/YouTube-Music#40]
Assume app is open but music is paused

I receive an incoming call which rings on my phone and mac via FaceTime app. For some reason music starts playing, in the same way as if I pressed the keyboard play key.

I've never seen this happen in an other situation, but it always happen every time I get a call

**Comment by naaronne** [comment]
I experience the same behavior

**Comment by douglas-queiroz** [comment]
I just fixed that issue on this pull request #58

**Comment by dmitrymikheev** [comment]
the same issue

**Comment by mmackh** [comment]
Issue still present on Monterey 12.6 - different devices. Anyone working on a fix? Otherwise I could look into it. Possible related #76 

Edit: Checked version on website and I was way out of date: 1.0.6 - updated to 1.3.3 to see if fixed.
